service: gustavo-aws-scrappy
frameworkVersion: '2'

plugins:
  - serverless-python-requirements

custom:
pythonRequirements:
    dockerizePip: non-linux
    
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  versionFunctions: false
  logRetentionInDays: 7 # used to set a global value for all functions
  timeout: 10 # optional, in seconds, default is 6

  iamRoleStatements: 
    - Effect: Allow
      Action:
        - execute-api:Invoke,
        - execute-api:ManageConnections
      Resource:
        - arn:aws:execute-api:*:*:*
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

functions:
  scrappyAmazon:
    handler: main.execute
    events:
      - schedule: rate(1 minute)
